# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Francois Roewer-Despres
email: francoisrd@cs.toronto.edu
description: >- # This means ignore new lines.
  I'm a PhD candidate at University of Toronto researching reasoning, grounding, and safety in large language models.
github_username: francois-rd
minimal_mistakes_skin: default
search: true

# Added by me based on https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
locale: "en-US"
url: https://francois-rd.github.io
name: Francois Roewer-Despres

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 50 # amount of posts to show
paginate_path: /page:num/
timezone: Canada/Eastern # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Hi, I'm Francois!"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD candidate at University of Toronto researching <b>reasoning</b>, <b>grounding</b>, and <b>safety</b> in large language models."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:francoisrd@cs.toronto.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/francois-rd"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/francois-rd"
    - label: "Scholar"
      icon: "ai fa-fw ai-google-scholar"
      url: "https://scholar.google.com/citations?user=uiA5W-YAAAAJ&hl=en" 

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:francoisrd@cs.toronto.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/francois-rd"
    - label: "Scholar"
      icon: "ai fa-fw ai-google-scholar"
      url: "https://scholar.google.com/citations?user=uiA5W-YAAAAJ&hl=en" 

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
